In [2]:
import torch
import numpy as np

c:\Users\chakr\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
#converting data to tensor
data = [[1,2],[3,4]]
print(data)
print(type(data))
X_data =  torch.tensor(data)
print(X_data)
print(type(X_data))

[[1, 2], [3, 4]]
<class 'list'>
tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>


In [4]:
#converting array to tensor
np_array = np.array([[1,2],[3,4]])
x_np = torch.from_numpy(np_array)
print(f"numpy array :- {np_array} and type {type(np_array)}")
print(f"pytorch tensor :- {x_np} and type {type(x_np)}")

numpy array :- [[1 2]
 [3 4]] and type <class 'numpy.ndarray'>
pytorch tensor :- tensor([[1, 2],
        [3, 4]], dtype=torch.int32) and type <class 'torch.Tensor'>


In [5]:
X_data

tensor([[1, 2],
        [3, 4]])

In [6]:
# From another tensor:
# The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden

x_ones = torch.ones_like(X_data) # retains the properties of x_data
x_rand = torch.rand_like(X_data, dtype=torch.float16) # # overrides the datatype of x_data

print(f"ones tensors: {x_ones}")
print(f"random tensors: {x_rand}")

ones tensors: tensor([[1, 1],
        [1, 1]])
random tensors: tensor([[0.6772, 0.9258],
        [0.4038, 0.6138]], dtype=torch.float16)


In [7]:
# creating 5*3 tensor 
t = torch.empty(5,3)
print(f"Created tensor {t} and shape of tensor {t.shape}")

Created tensor tensor([[9.9184e-39, 8.7245e-39, 9.2755e-39],
        [8.9082e-39, 9.9184e-39, 8.4490e-39],
        [9.6429e-39, 1.0653e-38, 1.0469e-38],
        [4.2246e-39, 1.0378e-38, 9.6429e-39],
        [9.2755e-39, 9.7346e-39, 1.0745e-38]]) and shape of tensor torch.Size([5, 3])


In [8]:
# randomaly initialize the tensor
x = torch.rand(5,3)
x

tensor([[0.2884, 0.7166, 0.8286],
        [0.9323, 0.1303, 0.4356],
        [0.2519, 0.4301, 0.4393],
        [0.3784, 0.9995, 0.6513],
        [0.4453, 0.4427, 0.4662]])

In [9]:
# Tensor operations
x = torch.rand(5,3)
y = torch.rand(5,3)

def tensor_operation():
    # addition operation
    z = x+y
    print(x+y)

In [10]:
# Resizing: If you want to reshape/resize a tensor, you can use “torch.view”:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) ## the size -1 is inferred from other dimensions
print(f"x -->{x.size()} , y -->{y.size()}, z--> {z.size()}")

x -->torch.Size([4, 4]) , y -->torch.Size([16]), z--> torch.Size([2, 8])


In [11]:
x = torch.randn(4,3)
z=x.view(-1,3)
z.size()

torch.Size([4, 3])

In [12]:
# Tensor to NumPy array
t = torch.ones(5)
n = t.numpy()
print(f"t: {t}-->{type(t)}")
print(f"n: {n}-->{type(n)}")

t: tensor([1., 1., 1., 1., 1.])--><class 'torch.Tensor'>
n: [1. 1. 1. 1. 1.]--><class 'numpy.ndarray'>


In [13]:
# NumPy array to Tensor
n = np.ones(5)
t = torch.from_numpy(n)
print(f"n: {n}-->{type(n)}")
print(f"t: {t}-->{type(t)}")


n: [1. 1. 1. 1. 1.]--><class 'numpy.ndarray'>
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)--><class 'torch.Tensor'>


In [18]:
x = torch.zeros(10, dtype=torch.float)
x

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])